services:
    UploadImageBundle\Service\FileUploader:
        arguments:
            $params: '@parameter_bag'
            $filesystem: '@filesystem'

 
 
    UploadImageBundle\Command\InstallUploadImageBundleCommand:
        arguments:
            $filesystem: '@filesystem'
            $params: '@parameter_bag'
        tags:
            - { name: 'console.command' }

  